### ISSUE TITLE
Code error in Readme.md

### ISSUE THREAD

**Issue by frankzhaopeng** [shimo-open/shimo-js-sdk#53]
![image](https://github.com/shimohq/shimo-js-sdk/assets/106129936/32d3da0e-97fc-45c5-a295-340ca6fde4c6)

Should it be written like this:

if (expires - Date.now() < 60000) {
}

Also, What if the user's local time is inaccurate, such as 2 minutes behind the actual time

**Comment by luyang950** [comment]
This is a simple demo to help users understand how to use the SDK, we do not currently account for inaccuracies in the user's browser time. However, theoretically, if such a situation arises, users may consider fetching the time from their own server.
